### ISSUE TITLE
clang -O2 and clang -fno-strict-aliasing -O2 run diff for the testcase csmith generated

### ISSUE THREAD

**Issue by yansendao** [csmith-project/csmith#102]
### csmith source version:
```
commit 0bd545feec35013caa8fa8732f12f8da28fa35be
Merge: 1d86f7c 2841ae1
Author: Xuejun Yang <nitsnow@gmail.com>
Date:   Sun Jul 19 16:58:36 2020 -0700

    Merge pull request #95 from mortior/remove-platform-info
    
    Add command line swithces for platform info and remove creation of platform.info file
```

Seed=1603344864136180

### on x86-64 platform(ubuntu20.04):

![image](https://user-images.githubusercontent.com/36258307/96839371-a95e6200-147b-11eb-8d2f-36b8306f0e80.png)

### compiler binary version:

![image](https://user-images.githubusercontent.com/36258307/96839446-cbf07b00-147b-11eb-8fd1-c5a303470940.png)

[test.c.txt](https://github.com/csmith-project/csmith/files/5420900/test.c.txt)

**Comment by eeide** [comment]
Hi! Thank you for reporting this.

Do you think this is a bug in Csmith, or do you think this is a bug in clang?

**Comment by yansendao** [comment]
> Hi! Thank you for reporting this.
> 
> Do you think this is a bug in Csmith, or do you think this is a bug in clang?

I think  it's a bug in Csmith.

**Comment by jxyang** [comment]
Could you elaborate more? @yansendao 

Many times we see this kind of behavior, we deem it to be a compiler bug, unless Csmith has generated code with undefined behaviors.

**Comment by yansendao** [comment]
> Could you elaborate more? @yansendao
> 
> Many times we see this kind of behavior, we deem it to be a compiler bug, unless Csmith has generated code with undefined behaviors.

https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#index-fstrict-aliasing

The reduce case like this:

```
#include <stdio.h>
union {
  long a;
  int b;
} c;
int d;
int *e = &c.b, *f;
long *g = &c.a;
int main() {
  for (; d <= 6; d = d + 3) {
    int h;
    *g = 0;
    f = &h;
    *e = 1;
  }
  printf("%d\n", c.b);
}
``

**Comment by jxyang** [comment]
Thanks for reducing the test case. It seems a rather interesting edge case of strict aliasing.

In the loop, the `a` field of the union is written, followed by `b` field the union get written. And the loop is guaranteed to be repeated 3 times. The end effect is that the the `b` field is the last written field after the loop, which makes reading the field via `c.b` in `printf` free of undefined behavior.

I noticed gcc produces "1" with or without `-fno-strict-aliasing`, leading me to believe this is a clang bug, not csmith's bug.
