### ISSUE TITLE
csmith 2.4.0 not published on the csmith site

### ISSUE THREAD

**Issue by chenrui333** [csmith-project/csmith#115]
👋  it looks like the csmith 2.4.0 did not get published on the site, `https://embed.cs.utah.edu/csmith/`

**Comment by jxyang** [comment]
Thanks. That was a test run. We will formally release 2.4.0 soon.

**Comment by chenrui333** [comment]
Sounds good, thanks @jxyang!

**Comment by thesamesam** [comment]
Fantastic, thank you & thanks for csmith!
