### ISSUE TITLE
Handle infinite loops in generated programs

### ISSUE THREAD

**Issue by mboussaa** [csmith-project/csmith#17]
csmith --bitfields --packed-struct -s 4256678765 > test.c;
gcc -I${CSMITH_PATH}/runtime -O -w test.c -o out.o;
./out 
doesn't provide any output 
Why?

**Comment by chenyang78** [comment]
First, just want to make sure that you executed ```out.o``` rather than ```out```? Second, the generated program ran into an infinite loop for me. It is an expected behavior, i.e., the generated code doesn't always terminate.

**Comment by mboussaa** [comment]
Thank you for your answer. However, To conduct compilers testing, I need that the program terminates at the end. Is there a way to tell csmith to generate programs without infinite loops?

**Comment by chenyang78** [comment]
No, csmith doesn't support that. Assuming that you have your own testing script and work on Linux-like systems, you can use ```timeout``` to terminate the execution. This is what we did.

**Comment by mboussaa** [comment]
ok I can see. I suggest to include this option flag to generated programs (e.g. --no-infinite-loop). For my experiments with Csmith, it is very useful to check for functional output.

**Comment by chenyang78** [comment]
In general, it's the halting problem.

**Comment by mboussaa** [comment]
Is there any attempt to fix that problem?

**Comment by chenyang78** [comment]
No, we didn't. I don't think we have any plan to address it.

**Comment by jxyang** [comment]
IIRC, most of the generate infinite loops either have a signed/unsigned
mismatch in the termination condition, e.g., "for (...; i >= 0; ....)"
while i is unsigned; or the control variable stays constant, e.g., "for (i
=0; i< 3; i+=0)". Neither of the two is too hard to avoid in Csmith. It's
just we get so accustomed to the timeout facility.

Halting problem is NP in general. But I think in this controlled
environment. avoiding non-halting is possible.

-Xuejun

**Comment by regehr** [comment]
Hi mboussaa, is there a reason why you cannot use timeouts? As Yang says, that is what we do.

**Comment by regehr** [comment]
Xuejun, I'm not sure it's as simple as you are making it sound. First, we would require some restrictions on goto. Second, modifications of loop variables would need to be constrained so that they don't break the termination property. It's not hard in principle of course.

**Comment by mboussaa** [comment]
Hi @regehr, technically timeouts work perfectly. I am measuring the execution time of each generated program. Terminating the program with timeout doesn't mean sense for my experiments. Sadly, the execution time will be always the same for different programs = timeout.

**Comment by regehr** [comment]
I would suggest a two-step process for your experiments. First, filter out the non-terminating programs; second, measure the execution time of the remaining programs. The end result is effectively identical to modifying Csmith so that it emits only terminating programs.

Alternatively, you could do the necessary Csmith modifications, but as I said above I'm not at all certain that they are so easy.

**Comment by mboussaa** [comment]
yes that what I have done. I was just wondering if there is a way of doing that on top level, I mean while generating csmith programs

**Comment by jxyang** [comment]
John, I think Csmith already has logic to avoid modifying loop induction
variables. Goto statements might be a problem, but they can be filtered out
with a Csmith flag.

**Comment by mboussaa** [comment]
Is it possible to ask csmith to generate large programs (for example more than 100k lines)?

**Comment by regehr** [comment]
Not directly, but there are various parameters such as number of functions and size of function that you can tweak, with the overall effect of increasing program size. Some experimentation will be required. Take a look at "csmith -h" and "csmith -hh".

**Comment by mboussaa** [comment]
Thank you. That is useful. However, as I said, I am seeking to test generated programs by csmith in term of execution time/memory footprint and so on. To do so, I have to generate very large programs that consume a lot of memory and have an execution time at least higher than 0.1s for example. I don't know which option flag should I set. Does any one has an idea to how handle that? 
Actually, random generated programs are not so greedy in term of system resources.  
Sorry if the question is out of the topic.
Thank you in advance.

**Comment by regehr** [comment]
Just generate random programs and throw them away until you find enough that have whatever characteristics you are looking for.

**Comment by mboussaa** [comment]
I should rely on which parameters to filter large programs? number of lines? file size? I don't know the value range of these parameters. It could take me too long time to find relevant programs for my case study.

**Comment by regehr** [comment]
Sorry, I don't think any of us has played with these parameters recently, some experimentation will be required on your part.

**Comment by eeide** [comment]
Re: generating large programs, these are probably the most useful command-line options:

--max-block-depth <num>: limit depth of nested blocks to <num> (default 5).
--max-block-size <size>: limit the number of non-return statements in a block to <size> (default 4).
--max-expr-complexity <num>: limit expression complexities to <num> (default 10).
--max-funcs <num>: limit the number of functions (besides main) to <num> (default 10).

Increasing these maximums will allow Csmith to generate larger programs. Even if you set these, Csmith will sometimes generate small programs: the above are maximums, not minimums. As @regehr wrote, if you want only big programs, the best strategy is to run Csmith repeatedly and filter out the programs you don't want. This is the technique that @regehr and I use when we want programs that meet certain criteria.

**Comment by eeide** [comment]
Re: generating memory-consuming programs, these are probably the most useful command-line options:

--max-array-dim <num>: limit array dimensions to <num>. (default 3)
--max-array-len-per-dim <num>: limit array length per dimension to <num> (default 10).
--max-struct-fields <num>: limit the number of struct fields to <num> (default 10).
--max-union-fields <num>: limit the number of union fields to <num> (default 5).

There is no direct control for overall memory consumption (just as there is no direct control for overall program size). But by increasing the maximums, you give Csmith the freedom to generate programs that potentially use more memory. Again, if you have some lower bound that you want all your tests to meet, the easiest strategy is to generate lots of programs and select the ones you want.
