### ISSUE TITLE
For loop variables over/underflow

### ISSUE THREAD

**Issue by alistairlow** [csmith-project/csmith#32]
When for loops are generated with '-=' or '+=' operations on the loop variable, code like the following can be output:

`for(i = 6; i != -6; i -= 5)`

This relies on underflow, and can result in a huge number of iterations of the loop. On X86 that is fine, but the test can take a very long time to run on simulated targets.

To prevent such wraparounds, the increment should exactly divide the difference between the loop variable's initial value and loop termination value, when the not-equal operator is used.

**Comment by jxyang** [comment]
That was intentional. The purpose was to expose compiler bugs with unexpected loops.

I will add a flag to do what you suggested. In fact, if there are additional changes required to speed up testing on simulated targets, list them here, and we will collapse them under the same flag.

**Comment by alistairlow** [comment]
Ok, thanks! We also noticed that very long-running loops can be generated with gotos. I will try to find an example.

Note that the comment at StatementFor.cpp:85 doesn't reflect your intention.

**Comment by regehr** [comment]
I'll just add that even on fast machines we always run Csmith-generated programs under a timeout.

**Comment by alistairlow** [comment]
Absolutely, the problem for us is that a program that takes seconds to run on X86 can take hours or days to run on a simulator, and we need to be able to differentiate between tests that are long-running and non-terminating.

**Comment by alistairlow** [comment]
A reduced example of a loop using gotos that runs for a large number of iterations:

`uint32_t l_8 = 0x5BFC88EBL;
lbl_11:
    l_8--;
    if (l_8)
        goto lbl_11;`

To reproduce, run "csmith --bitfields --no-divs --packed-struct -s 2040498876"

"for" loops that don't wrap around don't seem to run for so many iterations. We used the "--no-jumps" option to stop goto-based loops being generated, but perhaps an option to reduce the number of iterations would be better.

Recently, we also started using "--max-array-len-per-dim 5" to cut down time spent in loops where large structures are initialized.

Those are the only changes that we had to make to test in a reasonable amount of time on a simulator.

**Comment by jxyang** [comment]
It's very hard, if not impossible, to generate gotos that are guaranteed to run quickly. One way to address it is to only have forward jumps. For now, let's just use a flag "--fast-execution", and with it, I disabled jumps.

Please checkout the latest Csmith and make sure the slowness has been eliminiated with flag "--fast-execution".

**Comment by alistairlow** [comment]
I pulled the latest revision and it works well with --fast-execution. Thanks!
