### ISSUE TITLE
Unsigned loop variable underflow

### ISSUE THREAD

**Issue by alistairlow** [csmith-project/csmith#40]
We found another issue related to #32. Loops such as the following can be generated, where g_1475 is unsigned.

for (g_1475 = 8; (g_1475 >= 1); g_1475 = safe_sub_func_uint32_t_u_u(g_1475, 7))

Such underflow and wraparound can result in long-running tests on a simulator.

**Comment by jxyang** [comment]
So it's not only when `init == limit`, we have this wrap around. We should consider it's possible when `(limit - init) % incr == 0`
