### ISSUE TITLE
Assertion "invalid size!" failed.

### ISSUE THREAD

**Issue by alipourm** [csmith-project/csmith#42]
I am running Csmith 2.2.0, Git version: dcef523 on CentOS 7.

`$ ./csmith --no-argc --arrays --no-bitfields --checksum --comma-operators --compound-assignment --no-consts --divs --no-embedded-assigns --no-pre-incr-operator --no-pre-decr-operator --post-incr-operator --no-post-decr-operator --no-unary-plus-operator --jumps --no-longlong --int8 --no-uint8 --float --math64 --no-inline-function --muls --no-safe-math --packed-struct --paranoid --no-pointers --no-structs --unions --no-volatiles --no-volatile-pointers --no-const-pointers --builtins`

Csmith returns:
`csmith: SafeOpFlags.cpp:264: void SafeOpFlags::OutputSize(std::ostream&) const: Assertion !"invalid size!" failed.`

**Comment by chenyang78** [comment]
The issue was fixed by the patch sent by gergo-. Closing the ticket.
