### ISSUE TITLE
Couple of minor performance tweeks

### ISSUE THREAD

**Issue by dcb314** [csmith-project/csmith#48]
In response to

[trunk/src/StringUtils.cpp:177]: (performance) Inefficient usage of string::find() in condition; string::compare() would be faster.
[trunk/src/StringUtils.cpp:198]: (performance) Inefficient usage of string::find() in condition; string::compare() would be faster.

I made the following changes:

$ git diff src/StringUtils.cpp
diff --git a/src/StringUtils.cpp b/src/StringUtils.cpp
index 203982d..f6d2601 100644
--- a/src/StringUtils.cpp
+++ b/src/StringUtils.cpp
@@ -174,7 +174,8 @@ StringUtils::str2int(const std::string &s)
        }
        stringstream ss(s);
        int i = -1;
-       if (s.find("0x")==0) {
+       // if (s.find("0x")==0) {
+       if (s.compare(0, 2, "0x") == 0) {
                ss >> std::hex >> i;
        } else {
                ss >> i;
@@ -195,7 +196,8 @@ StringUtils::str2longlong(const std::string &s)
 {
        INT64 i = 0;
        size_t j;
-       if (s.find("0x")==0) {
+       // if (s.find("0x")==0) {
+       if (s.compare(0, 2, "0x") == 0) {
                for (j=2; j<s.length(); j++) {
                        int v = 0;
                        if (s[j] >= '0' && s[j] <= '9') {
$

**Comment by dcb314** [comment]
Let's have a second try at that code

`$ git diff StringUtils.cpp
diff --git a/src/StringUtils.cpp b/src/StringUtils.cpp
index 203982d..f6d2601 100644
--- a/src/StringUtils.cpp
+++ b/src/StringUtils.cpp
@@ -174,7 +174,8 @@ StringUtils::str2int(const std::string &s)
        }
        stringstream ss(s);
        int i = -1;
-       if (s.find("0x")==0) {
+       // if (s.find("0x")==0) {
+       if (s.compare(0, 2, "0x") == 0) {
                ss >> std::hex >> i;
        } else {
                ss >> i;
@@ -195,7 +196,8 @@ StringUtils::str2longlong(const std::string &s)
 {
        INT64 i = 0;
        size_t j;
-       if (s.find("0x")==0) {
+       // if (s.find("0x")==0) {
+       if (s.compare(0, 2, "0x") == 0) {
                for (j=2; j<s.length(); j++) {
                        int v = 0;
                        if (s[j] >= '0' && s[j] <= '9') {
$ `

**Comment by jxyang** [comment]
Looks good. Can you modify this for other instances of string::find and make a pull request?

**Comment by dcb314** [comment]
>Looks good.

Thanks. Here are some similar cases.

trunk/src/ReducerOutputMgr.cpp:269]: (performance) Inefficient usage of string::find() in condition; string::compare() would be faster.

and

[trunk/src/Reducer.cpp:103]: (performance) Inefficient usage of string::find() in condition; string::compare() would be faster.
[trunk/src/Reducer.cpp:1207]: (performance) Inefficient usage of string::find() in condition; string::compare() would be faster.
[trunk/src/Reducer.cpp:129]: (performance) Inefficient usage of string::find() in condition; string::compare() would be faster.
[trunk/src/Reducer.cpp:136]: (performance) Inefficient usage of string::find() in condition; string::compare() would be faster.
[trunk/src/Reducer.cpp:144]: (performance) Inefficient usage of string::find() in condition; string::compare() would be faster.
[trunk/src/Reducer.cpp:156]: (performance) Inefficient usage of string::find() in condition; string::compare() would be faster.
[trunk/src/Reducer.cpp:165]: (performance) Inefficient usage of string::find() in condition; string::compare() would be faster.
[trunk/src/Reducer.cpp:169]: (performance) Inefficient usage of string::find() in condition; string::compare() would be faster.
[trunk/src/Reducer.cpp:173]: (performance) Inefficient usage of string::find() in condition; string::compare() would be faster.
[trunk/src/Reducer.cpp:177]: (performance) Inefficient usage of string::find() in condition; string::compare() would be faster.
[trunk/src/Reducer.cpp:181]: (performance) Inefficient usage of string::find() in condition; string::compare() would be faster.
[trunk/src/Reducer.cpp:185]: (performance) Inefficient usage of string::find() in condition; string::compare() would be faster.
[trunk/src/Reducer.cpp:189]: (performance) Inefficient usage of string::find() in condition; string::compare() would be faster.

**Comment by jxyang** [comment]
@dcb314 Please submit a pull request and we can discussed the details there.

**Comment by dcb314** [comment]
I just find bugs, I don't fix them. 

Folks who know the code much better than I do are in a much better position to fix them.

Unless you think some random person off t'Internet is the best person to have write
permission on your repository.

**Comment by jensgerlach** [comment]
Hello,

It is perfectly fine if you don’t want to fix their code.

I just would like to point out that the developers don’t have to grant you write access to their repository.
“pull-requests” have been invented to solve the problem of safely incorporating someone else’s code.

Regards

Jens

Von: dcb314 <notifications@github.com>


I just find bugs, I don't fix them.

Folks who know the code much better than I do are in a much better position to fix them.

Unless you think some random person off t'Internet is the best person to have write
permission on your repository.

**Comment by jxyang** [comment]
No pull request. Closing.
