### ISSUE TITLE
Packaging friendliness: misc support utilities unsuitable for use as installed

### ISSUE THREAD

**Issue by dtzWill** [csmith-project/csmith#51]
(I maybe accidentally filed an issue here I didn't mean to, so I'm salvaging things by turning this into a real issue ;))

Lots of minor issues, thought I'd record them in case they can be fixed.  These are issues that would be encountered in packaging for any distribution, but were encountered while packaging for NixOS:

https://github.com/dtzWill/nixpkgs/blob/5516a2b6a14f30788575913fbf998b379b17fc2c/pkgs/development/tools/misc/csmith/default.nix

* Headers are installed, but utilities still try to find them in a source directory pointed to by CSMITH_HOME environment variable.
* `compiler_test.pl` doesn't find `csmith` relative to itself, instead looks for it relative to CSMITH_HOME
* `compiler_test.in` is installed to `$binDir`, which is strange since it isn't intended for direct execution (so it shouldn't be on a user's PATH by default) AFAICT.  I put it in /share/csmith/compiler-test.in but perhaps a better place would be libexec?
* `launchn.pl` looks for 'config files' in a parent directory, which doesn't work so well an installation.

Dependency on perl and in particular Sys::CPU is not mentioned in the documentation, which might be worth mentioning.

While I'm at it, looks like Debian has some patches they maintain for packaging csmith that might be suitable for inclusion upstream:

[Debian csmith package page](https://packages.debian.org/sid/devel/csmith)
[Debian tarball with patches and such](http://http.debian.net/debian/pool/main/c/csmith/csmith_2.2.0-2.debian.tar.xz)

**Comment by dtzWill** [comment]
..... I have too many github tabs open, sorry this was entirely the wrong repo! :innocent: 

(If you're able to delete this issue that's probably for the best...)

**Comment by eeide** [comment]
Thanks.

I agree that the "miscellaneous binaries" are not very well packaged.

My general opinion is that `make install` should probably not install the miscellaneous binaries at all, although I expect that we would continue to distribute them. Either that, or we need to put some real effort into making a more robust compiler-test driver—probably more work than is outlined above.

**Comment by eeide** [comment]
I took a quick look at the patches in the Debian package. They are pretty small, and maybe two of them (futzing with `platform.cpp`) are obsolete for Csmith 2.3.0?

Anyway, I'll reconsider them again before closing this issue.

Thanks for the pointer—

**Comment by dtzWill** [comment]
@eeide this is a very good point, and an important distinction.  I've updated the issue title to better reflect that this is really only about the "miscellaneous" scripts that are packaged as well.

As a result I think this issue is only useful as maybe somewhat informative, but regardless I don't see much of a case for any action in order to address this (as far as I'm concerned).  Please proceed however you see fit, sorry for the noise :).

**Comment by jxyang** [comment]
Superseded by #68, which should address the problems outlined here.
