### ISSUE TITLE
Cannot get the hacked lcov

### ISSUE THREAD

**Issue by BambooL** [csmith-project/csmith#54]
When I tried to fetch the hacked lcov through:
svn co svn+ssh://shell.cs.utah.edu/uusoc/res/embed/users/regehr/embedded_code_repo/yang/coverage/lcov-1.8 lcov-1.8
it requires authorization.

**Comment by eeide** [comment]
I don't have any context for this issue. Do you, @regehr?

It is true that you would need authorization to get to the SVN repository that you mentioned, but I don't understand why you are trying to get to it.

**Comment by BambooL** [comment]
Thanks for the quick response. I am trying to conduct the coverage test as indicated here: https://github.com/csmith-project/csmith/tree/master/utah/scripts/coverage

**Comment by eeide** [comment]
Thanks for the explanation.

I'll leave this issue in @regehr's hands for now.

I will mention, though, that the stuff in the `utah` directory is not really part of "the Csmith distribution" and is unsupported. (Notice how the `README` in that directory also tells the reader to get Csmith from a long-obsolete repository!)

**Comment by regehr** [comment]
Yeah, hi @BambooL, I'm sorry but this is some really old code that I think all of us had forgotten about. I doubt the recipes here work anymore and I don't think any of us is going to update it.

Really, this utah directory needs to be nuked from Csmith, though I'm not going to do that right now.

Wish I had a better answer for you!
