### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [csmith-project/csmith#57]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
* [DEPTH_GUARD_BY_DEPTH_RETURN_DEL1](https://github.com/csmith-project/csmith/blob/8ade51fc46201d01e528b98c179e9f7a2e37b58e/src/DepthSpec.h#L92)
* [Function::deleteFunction](https://github.com/csmith-project/csmith/blob/8ade51fc46201d01e528b98c179e9f7a2e37b58e/src/RandomNumber.cpp#L168)
* [RandomNumber::doFinalization](https://github.com/csmith-project/csmith/blob/8ade51fc46201d01e528b98c179e9f7a2e37b58e/src/RandomNumber.cpp#L168)
* [Variable](https://github.com/csmith-project/csmith/blob/8ade51fc46201d01e528b98c179e9f7a2e37b58e/src/Variable.cpp#L470 "Destructor for Variable")

**Comment by regehr** [comment]
We would likely accept a pull request fixing these.

**Comment by elfring** [comment]
How do you think about to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability-delete-null-pointer.html "Deletion of unnecessary null pointer checks")?

**Comment by jxyang** [comment]
Merged. Thanks!
