### ISSUE TITLE
Catch exceptions in main()?

### ISSUE THREAD

**Issue by elfring** [csmith-project/csmith#58]
I expect that exception handling is usually supported by a C++ program. I wonder why your function “[main](https://github.com/csmith-project/csmith/blob/8ade51fc46201d01e528b98c179e9f7a2e37b58e/src/RandomProgramGenerator.cpp#L351 "main() function")” does not contain [corresponding try and catch instructions](https://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main "Does it make sense to catch exceptions in the main(…)?") so far.

How do you think about recommendations by Matthew Wilson in [an article](https://accu.org/index.php/journals/1706 "Quality Matters #6: Exceptions for Practically-Unrecoverable Conditions")?

Would you like to adjust the implementation if you consider [effects for uncaught/unhandled exceptions](https://en.cppreference.com/w/cpp/language/try_catch "Description for exception handling")?

**Comment by elfring** [comment]
Would you like to care for consequences from uncaught/unhandled exceptions around information like “…, it is implementation-defined whether any stack unwinding occurs at all …”?

**Comment by regehr** [comment]
Please give a concrete example of a situation where a try/catch block would be helpful to Csmith's users.

**Comment by elfring** [comment]
Do you care if C++ destructors will be called (for Csmith's objects) in exceptional software situations?

**Comment by regehr** [comment]
Wait, you are talking about Csmith itself, not Csmith's generated code? Anyway, in either case the answer is "no."

**Comment by elfring** [comment]
Are you pleased with the implementation-defined behaviour of the involved C++ compilers so far?

**Comment by regehr** [comment]
Sorry, I am not interested in discussing this implementation-defined behavior of C++ compilers.
