### ISSUE TITLE
Building under Cygwin fails (`srand48`, 'lrand48' not declared)

### ISSUE THREAD

**Issue by versat** [csmith-project/csmith#83]
I try to build current HEAD via
```
cmake .
make
```
under the latest Cygwin (CMake 3.14.5, GCC 7.4.0), but it fails:
```
/cygdrive/e/Files/GitHub/csmith/src/AbsRndNumGenerator.cpp: In static member function ‘static void AbsRndNumGenerator::seedrand(long unsigned int)’:
/cygdrive/e/Files/GitHub/csmith/src/AbsRndNumGenerator.cpp:98:2: error: ‘srand48’ was not declared in this scope
  srand48(seed);
  ^~~~~~~
/cygdrive/e/Files/GitHub/csmith/src/AbsRndNumGenerator.cpp:98:2: note: suggested alternative: ‘_rand48’
  srand48(seed);
  ^~~~~~~
  _rand48
/cygdrive/e/Files/GitHub/csmith/src/AbsRndNumGenerator.cpp: In member function ‘virtual long unsigned int AbsRndNumGenerator::genrand()’:
/cygdrive/e/Files/GitHub/csmith/src/AbsRndNumGenerator.cpp:131:9: error: ‘lrand48’ was not declared in this scope
  return lrand48();
         ^~~~~~~
/cygdrive/e/Files/GitHub/csmith/src/AbsRndNumGenerator.cpp:131:9: note: suggested alternative: ‘_rand48’
  return lrand48();
         ^~~~~~~
         _rand48
make[2]: *** [src/CMakeFiles/csmith.dir/build.make:89: src/CMakeFiles/csmith.dir/AbsRndNumGenerator.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:260: src/CMakeFiles/csmith.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
One problem is that https://github.com/csmith-project/csmith/blob/master/src/AbsRndNumGenerator.cpp includes the header `cstdlib`, but in [https://github.com/csmith-project/csmith/blob/master/CMakeLists.txt](https://github.com/csmith-project/csmith/blob/900729af2f1f4cb01805181b2a03ea142647a51b/CMakeLists.txt#L103) `lrand48` is searched in `stdlib.h`. At least under Cygwin it seems that `srand48` and `lrand48` are only directly available when included via `#include <stdlib.h>` but not when included via `#include <cstdlib>`.

I am not sure how to best fix this issue since there are other places where `stdlib.h` is included. So simply changing it in CMakeList.txt does not really fix it I guess, at least maybe not in a clean way.
`make` can compile `AbsRndNumGenerator.cpp` then, but there is the next issue with `arc4random_buf` then in `platform.cpp`:
```
/cygdrive/e/Files/GitHub/csmith/src/platform.cpp: In function ‘long unsigned int platform_gen_seed()’:
/cygdrive/e/Files/GitHub/csmith/src/platform.cpp:108:2: error: ‘arc4random_buf’ was not declared in this scope
  arc4random_buf(&seed, sizeof seed);
  ^~~~~~~~~~~~~~
make[2]: *** [src/CMakeFiles/csmith.dir/build.make:947: src/CMakeFiles/csmith.dir/platform.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:260: src/CMakeFiles/csmith.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
Looking at the `stdlib.h` I can see that `__BSD_VISIBLE` needs to be defined for the `arc4random*` functions to be available.

Maybe completely switching to C++ headers where it is possible and use [check_cxx_symbol_exists](https://cmake.org/cmake/help/latest/module/CheckCXXSymbolExists.html#module:CheckCXXSymbolExists) instead of `check_symbol_exists` would be a solution?

**Comment by jxyang** [comment]
We haven't built Csmith on Cygwin for 7 years. It's possible they have shuffled the function definitions in headers so that `arc4random*` is no longer available. I think the simplest solution is to add an definition for Cygwin at this line : https://github.com/csmith-project/csmith/blob/900729af2f1f4cb01805181b2a03ea142647a51b/src/platform.cpp#L60, so that it uses `read_time` instead.

**Comment by jxyang** [comment]
Is there any reason you are not using WSL on windows? As I just tried, Csmith works with wsl, and the performance is much better than cygwin.

https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by versat** [comment]
> Is there any reason you are not using WSL on windows? As I just tried, Csmith works with wsl, and the performance is much better than cygwin.
> 
> https://docs.microsoft.com/en-us/windows/wsl/install-win10

Great to know. The reason for using Cygwin simply was that I used Windows 7 back then where WSL was not available.
Today Windows 7 really should not be used any longer, so I agree that WSL is an alternative.
