### ISSUE TITLE
What code can't csmith generate？

### ISSUE THREAD

**Issue by Hanseltu** [csmith-project/csmith#85]
Hi, I am considering generating some special programs to test the c compiler. The tool csmith is very cool. I want to know if there is a specific program (recursive functions, etc.) that csmith has no way to generate but can effectively test the compiler ? 

Any suggestions are welcome, thanks.

**Comment by regehr** [comment]
Hi! There are many, many interesting constructs that Csmith cannot generate. One of the big things is that the guard code used to dynamically avoid undefined behavior limit expressiveness. Here are some others:
- Strings
- Floating point
- Nonlocal jumps
- Variadic functions
- Recursion
- Function pointers
- malloc / free

**Comment by eeide** [comment]
Also, calls to standard library functions that compilers may treat specially.

**Comment by regehr** [comment]
Something I would specifically stress test if I was doing this work now is function attribute inference. The semantics of these is often pretty unclear and I suspect they can be used to generate miscompiles.
https://llvm.org/docs/LangRef.html#function-attributes

**Comment by Hanseltu** [comment]
Thanks for your all warm-hearted and valuable suggestions!  I will carefully consider the above perspectives then do something, and I will share it with you if I make any progress.
