### ISSUE TITLE
Frequently raising Floating point exception under restricted options

### ISSUE THREAD

**Issue by hyunsukimsokcho** [csmith-project/csmith#87]
I am running Csmith 2.3.0 (+libcsmith-dev 2.3.0), Git version: [30dccd7](https://github.com/csmith-project/csmith/commit/30dccd73b78652c4719f36572994778a5b233a4e) on Ubuntu 18.04 with the following version of production level compilers:
gcc version: 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04). 
clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)

`$ csmith --no-argc --no-arrays --no-jumps --no-longlong --no-int8 --no-uint8 --no-safe-math --no-pointers --no-structs --no-unions --no-builtins`

Although random programs are well-generated and can be compiled, it raises `Floating point exception (core dumped)` as we execute. I observed the situation occurring quite often. (For me, about three cases raise FPE out of five trials - 60% chance failure) It happens for both gcc and clang.

I was able to cut down one of the program (raising FPE):
```c
#include "csmith.h"
a;
b(int16_t d, uint32_t f, uint32_t g) {
  if (f / 0) {
    uint16_t h = 5;
  }
}
c() {}
main() {
  int32_t e;
  b(c, e, a);
}
```

As one may easily observe, `f / 0` in line no.4, results in division-by-zero. I wonder if this is plausible property of a random program generated from Csmith, or any how our misuse of conflicting Csmith options.

Side-note: I saw the latest [commit](https://github.com/csmith-project/csmith/commit/27ace5bd643642c20064734343e90da62b54d7fa) by @chenyang78 and wonder if it is the patch for this issue.

---
P.S. Me and my colleagues are using Csmith to fuzz our own C compiler, [KECC](https://github.com/kaist-cp/kecc) which is written in Rust. (still under construction!) It is for educational purposes especially in [this course](https://github.com/kaist-cp/cs420). We really appreciate your well-made fuzzer and reducer (Creduce) as well.

**Comment by chenyang78** [comment]
@hyunsukimsokcho Thank you for reporting this. It's very unlikely the failure was caused by my commit, which only has effect if ```--strict-float``` is passed. I reverted my commit locally, and tried with your options. I observed the same behaviour as you described - a lot of FPE failures. We will investigate it. Thanks.

**Comment by chenyang78** [comment]
OK. I noticed that you passed ```--no-safe-math``` to csmith. The use of this option was the cause of those FPE failures. Csmith relies on "safe-math" functions to ensure the well-behavior of the generated programs at runtime. Please don't use ```--no-safe-math``` if you want to run the executables. Thanks.

**Comment by hyunsukimsokcho** [comment]
Thanks for the prompt response! We will definitely try the option. Closing for now.

**Comment by hyunsukimsokcho** [comment]
@chenyang78 Though many days have passed, we were able to resolve FPE-raising issue. Indeed, after some investigation, we presumably found Csmith doesn't actually do any math with float variables. (Even with or without `--no-safe-math`) Is this the intended  behavior, or somehow our study may have been misguided by any chance?
