### ISSUE TITLE
seeds all the same when generate testcase concurrently

### ISSUE THREAD

**Issue by yansendao** [csmith-project/csmith#91]
test command：

seq 5 | xargs -i -n 1 -P 5 bash -c "csmith | grep -w Seed"

result：

![image](https://user-images.githubusercontent.com/36258307/82324182-d198ef00-9a0b-11ea-9e0f-1ccbb5893700.png)

csmith version：
```
$ csmith -v
csmith 2.4.0
Git version: 5039909
```

fix method:
```diff
$ git diff
diff --git a/src/platform.cpp b/src/platform.cpp
index ff69361..d1ef1f9 100644
--- a/src/platform.cpp
+++ b/src/platform.cpp
@@ -46,6 +46,7 @@
 
 #include "platform.h"
 #include <stdlib.h>
+#include <sys/time.h>
 #if HAVE_BSD_STDLIB_H
 #  include <bsd/stdlib.h>
 #endif
@@ -111,7 +112,10 @@ unsigned long platform_gen_seed()
 #else
 unsigned long platform_gen_seed()
 {
-       return (long) read_time();
+       //return (long) read_time();
+       struct timeval tp;
+       gettimeofday(&tp, nullptr);
+       return tp.tv_sec * 1000000 + tp.tv_usec;
 }
 #endif
```

![image](https://user-images.githubusercontent.com/36258307/82324337-0dcc4f80-9a0c-11ea-87e8-48a355ee34ca.png)

**Comment by jxyang** [comment]
Just curious which platform are you on? Generally Csmith prefers to use hardware timestamp counters (if available) as the seeds. Seems you are on a platform that has to get the clock as the seed. While we are here, why don't we use clock_gettime that gives us an even higher precision clock?

**Comment by yansendao** [comment]
> Just curious which platform are you on? Generally Csmith prefers to use hardware timestamp counters (if available) as the seeds. Seems you are on a platform that has to get the clock as the seed. While we are here, why don't we use clock_gettime that gives us an even higher precision clock?

I am on aarch64 mathine:

```
$ lscpu 
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              96
On-line CPU(s) list: 0-95
Thread(s) per core:  1
Core(s) per socket:  48
Socket(s):           2
NUMA node(s):        4
Vendor ID:           0x48
Model:               0
Stepping:            0x1
BogoMIPS:            200.00
L1d cache:           64K
L1i cache:           64K
L2 cache:            512K
L3 cache:            49152K
NUMA node0 CPU(s):   0-23
NUMA node1 CPU(s):   24-47
NUMA node2 CPU(s):   48-71
NUMA node3 CPU(s):   72-95
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop asimddp asimdfhm
```

**Comment by yansendao** [comment]
clock_gettime seems get all the same seed when generate testcase concurrently

![image](https://user-images.githubusercontent.com/36258307/95649890-9d38e300-0b12-11eb-89a2-b02af47899ca.png)

**Comment by regehr** [comment]
I would suggest generating seeds however you like, and passing these to Csmith.

the clock-based seeding is only for convenience when the user fails to specify a seed.

**Comment by jxyang** [comment]
See my suggestion in #101. 

Alternatively, we can have Csmith taking another command line parameter `machine ID`, which is considered while generating a seed.

**Comment by jxyang** [comment]
Dup of #101
