### ISSUE TITLE
testcase run over than 10 hours when seed = 1589891333747081

### ISSUE THREAD

**Issue by yansendao** [csmith-project/csmith#92]
test command:
```
clang -I/home/yansendao/software/csmith/include/csmith-2.4.0 test.c -o clang-a.out  -O3
time timeout 10h ./clang-a.out
```

![image](https://user-images.githubusercontent.com/36258307/82397328-cd5be880-9a82-11ea-8780-e7708ed67088.png)

clang version 10.0.0

[test.c.txt](https://github.com/csmith-project/csmith/files/4654268/test.c.txt)

**Comment by eeide** [comment]
The programs generated by Csmith are not guaranteed to terminate. For this reason, you'll probably want to run them under some kind of timeout.

**Comment by regehr** [comment]
in our experience, most generated programs that are going to terminate do so fairly quickly, so this timeout doesn't really need to be that long
